use super::*;

// ── handle_osc_default_colors (OSC 12 query, unknown OSC number) ──────────────

test_osc_default_colors_query_set!(
    test_handle_osc_default_colors_query_cursor_color_produces_response,
    b"12",
    cursor_color,
    0,
    0,
    255
);

#[test]
fn test_handle_osc_default_colors_unknown_osc_number_set_changes_no_color() {
    // OSC number "99" is not 10/11/12 — the `_ => {}` match arm fires, so no
    // color field is written.  However, `default_colors_dirty` is set
    // unconditionally inside `if let Some([r,g,b])` once the color spec parses,
    // which is the existing behavior.
    let mut core = make_core!();
    let params: &[&[u8]] = &[b"99", b"#ff0000"];
    super::handle_osc_default_colors(&mut core, params);
    assert!(
        core.osc_data().default_fg.is_none(),
        "unknown OSC must not set default_fg"
    );
    assert!(
        core.osc_data().default_bg.is_none(),
        "unknown OSC must not set default_bg"
    );
    assert!(
        core.osc_data().cursor_color.is_none(),
        "unknown OSC must not set cursor_color"
    );
    // default_colors_dirty is set by the current implementation after any valid
    // color-spec parse, even for unknown OSC numbers.
    assert!(core.osc_data().default_colors_dirty);
}

#[test]
fn test_handle_osc_default_colors_unknown_osc_number_query_is_noop() {
    // OSC number "99" with query — the `_ => return` branch fires; no response pushed.
    let mut core = make_core!();
    let params: &[&[u8]] = &[b"99", b"?"];
    super::handle_osc_default_colors(&mut core, params);
    assert!(
        core.pending_responses().is_empty(),
        "unknown OSC number query must push no response"
    );
}

#[test]
fn test_handle_osc_default_colors_query_unset_cursor_color_responds_grey() {
    // cursor_color is None — query must respond with fallback grey (128, 128, 128).
    let mut core = make_core!();
    let params: &[&[u8]] = &[b"12", b"?"];
    super::handle_osc_default_colors(&mut core, params);
    assert_eq!(core.pending_responses().len(), 1);
    let resp = std::str::from_utf8(&core.pending_responses()[0]).unwrap();
    assert!(
        resp.contains("8080"),
        "unset cursor color query must respond with grey (0x8080): got {resp:?}"
    );
}

// ── New edge-case tests ────────────────────────────────────────────────────────

/// `parse_color_spec` with 1-digit channels treats them as ≤2-digit (value used directly).
///
/// The `normalize` function uses `digits > 2` to decide between 4-digit (shift-right-8)
/// and short-form (direct) modes, so "f" → `u16 = 15` → `15 as u8`.
#[test]
fn test_parse_color_spec_rgb_single_digit_channel_direct_value() {
    // 1-digit channels: digits ≤ 2, so value is used directly without shifting.
    // "f" = 0x0F = 15, "8" = 8, "0" = 0
    assert_eq!(parse_color_spec("rgb:f/8/0"), Some([15, 8, 0]));
}

/// `parse_color_spec` with 3-digit channels treats them as >2-digit (upper 8 bits used).
///
/// The `normalize` function uses `digits > 2`, so 3-digit "fff" → `u16 = 0x0FFF` →
/// `(0x0FFF >> 8) as u8 = 0x0F = 15`.
#[test]
fn test_parse_color_spec_rgb_3digit_channel_uses_upper_byte() {
    // 3-digit channels: digits > 2, so upper 8 bits are taken.
    // "fff" = 0x0FFF → 0x0FFF >> 8 = 0x0F = 15; "000" → 0
    assert_eq!(parse_color_spec("rgb:fff/000/000"), Some([15, 0, 0]));
}

// Palette boundary reset tests — generated by `test_osc_104_reset_index!`.
// index 0: first ANSI color
test_osc_104_reset_index!(test_handle_osc_104_index_0_boundary, 0, [10, 20, 30]);
// index 16: first 256-color cube entry
test_osc_104_reset_index!(test_handle_osc_104_index_16_boundary, 16, [0, 0, 0]);
// index 231: last 6×6×6 color cube entry
test_osc_104_reset_index!(test_handle_osc_104_index_231_boundary, 231, [255, 255, 255]);
// index 232: first greyscale-ramp entry
test_osc_104_reset_index!(test_handle_osc_104_index_232_boundary, 232, [8, 8, 8]);

/// Prompt mark at cursor row 0 (top-left boundary).
#[test]
fn test_handle_osc_133_mark_records_row_zero() {
    use crate::types::osc::PromptMark;
    let mut core = make_core!();
    // Cursor starts at (0, 0) after construction — no CUP needed.
    let params: &[&[u8]] = &[b"133", b"A"];
    super::handle_osc_133(&mut core, params);
    assert_eq!(core.osc_data().prompt_marks.len(), 1);
    let ev = &core.osc_data().prompt_marks[0];
    assert_eq!(ev.mark, PromptMark::PromptStart);
    assert_eq!(ev.row, 0, "row must be 0 at top-left boundary");
    assert_eq!(ev.col, 0, "col must be 0 at top-left boundary");
}

/// `encode_color_spec` on a single-component boundary value: only the blue
/// channel is non-zero, with value 1 (the lowest non-zero 8-bit value).
#[test]
fn test_encode_color_spec_single_component_min_nonzero() {
    // 0x01 expands to 0x0101 in 16-bit
    let result = encode_color_spec([0, 0, 1]);
    assert_eq!(result, "rgb:0000/0000/0101");
}

use proptest::prelude::*;

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]

    #[test]
    // PANIC SAFETY: OSC 133 (prompt mark) with any mark type string never panics
    fn prop_osc133_mark_no_panic(
        mark in prop_oneof![Just("A"), Just("B"), Just("C"), Just("D"), Just("Z")]
    ) {
        let mut term = crate::TerminalCore::new(24, 80);
        let seq = format!("\x1b]133;{mark}\x07");
        term.advance(seq.as_bytes());
        prop_assert!(term.screen.cursor().row < 24);
    }

    #[test]
    // PANIC SAFETY: OSC 7 (cwd) with arbitrary URI never panics
    fn prop_osc7_arbitrary_uri_no_panic(
        path in proptest::collection::vec(b'a'..=b'z', 1..=50)
    ) {
        let mut term = crate::TerminalCore::new(24, 80);
        let path_str = String::from_utf8(path).unwrap_or_default();
        let seq = format!("\x1b]7;file://localhost/{path_str}\x07");
        term.advance(seq.as_bytes());
        prop_assert!(term.screen.cursor().row < 24);
    }

    #[test]
    // PANIC SAFETY: OSC 1337 with arbitrary payload never panics
    fn prop_osc1337_no_panic(
        payload in proptest::collection::vec(b'a'..=b'z', 0..=50)
    ) {
        let mut term = crate::TerminalCore::new(24, 80);
        let p = String::from_utf8(payload).unwrap_or_default();
        let seq = format!("\x1b]1337;{p}\x07");
        term.advance(seq.as_bytes());
        prop_assert!(term.screen.cursor().row < 24);
    }
}
