;;; kuro-input-keys-test.el --- Tests for kuro-input-keys.el  -*- lexical-binding: t; -*-

;; Copyright (C) 2025 takeokunn

;; Author: takeokunn
;; Version: 1.0.0

;;; Commentary:

;; ERT tests for kuro-input-keys.el special key handlers.
;; These tests exercise:
;;   - F1-F12 function key handlers (SS3/CSI sequences)
;;   - Arrow key handlers (normal mode sequences)
;;   - Home/End/Insert/Delete/PageUp/PageDown handlers
;;   - Modifier key senders (ctrl-modified, alt-modified)
;;
;; Pure Elisp tests -- no Rust dynamic module required.
;; All FFI dependencies are stubbed before requiring the module.

;;; Code:

(require 'kuro-input-keys-test-support)

;;; Groups 1-4: Key sequence handlers

(kuro-input-keys-test--deftest-sequence-cases
  kuro-input-keys-test--primary-sequence-cases)

(ert-deftest kuro-input-keys--f6-through-f12-send-correct-sequences ()
  "F6-F12 handlers send the correct CSI sequences."
  (dolist (pair (kuro-input-keys-test--function-sequence-range 5 12))
    (kuro-input-keys-test--with-capture
      (funcall (car pair))
      (should (equal (car kuro-input-keys-test--sent) (cdr pair))))))

;;; Group 5: Modifier helpers

(kuro-input-keys-test--deftest-ctrl-modified-cases)
(kuro-input-keys-test--deftest-alt-modified-cases)

;;; Group 6: kuro--def-key-sequence macro validation

(ert-deftest kuro-input-keys--def-key-sequence-generates-interactive-fn ()
  "kuro--def-key-sequence generates an interactive function."
  (kuro--def-key-sequence kuro--test-seq-fn
    "Test sequence function." "\e[TEST" "\eOTEST")
  (should (fboundp 'kuro--test-seq-fn))
  (should (commandp 'kuro--test-seq-fn)))

(ert-deftest kuro-input-keys--def-key-sequence-sends-normal-seq-in-normal-mode ()
  "Macro-generated function sends normal sequence in normal cursor mode."
  (kuro--def-key-sequence kuro--test-normal-fn
    "Test normal mode." "\e[NORM" "\eOAPP")
  (kuro-input-keys-test--with-capture
    (kuro-input-keys-test--with-cursor-mode nil
      (kuro--test-normal-fn)
      (should (equal (car kuro-input-keys-test--sent) "\e[NORM")))))

(ert-deftest kuro-input-keys--def-key-sequence-sends-app-seq-in-app-mode ()
  "Macro-generated function sends application sequence in application cursor mode."
  (kuro--def-key-sequence kuro--test-app-fn
    "Test app mode." "\e[NORM" "\eOAPP")
  (kuro-input-keys-test--with-capture
    (kuro-input-keys-test--with-cursor-mode t
      (kuro--test-app-fn)
      (should (equal (car kuro-input-keys-test--sent) "\eOAPP")))))

(ert-deftest kuro-input-keys--all-22-handlers-are-bound ()
  "All 22 key sequence handlers generated by kuro--def-key-sequence are fboundp."
  (dolist (fn (kuro-input-keys-test--all-sequence-handlers))
    (should (fboundp fn))))

(ert-deftest kuro-input-keys--ctrl-modified-modifier-arg-ignored ()
  "kuro--ctrl-modified ignores the MODIFIER argument (reserved for future use)."
  (kuro-input-keys-test--with-capture
    ;; Same char, different modifier values — result must be identical
    (kuro--ctrl-modified ?b 0)
    (let ((sent-0 (car kuro-input-keys-test--sent)))
      (setq kuro-input-keys-test--sent nil)
      (kuro--ctrl-modified ?b 4)
      (should (equal sent-0 (car kuro-input-keys-test--sent))))))

;;; Group 8: kuro--alt-modified render scheduling

(ert-deftest kuro-input-keys--alt-modified-triggers-render-schedule ()
  "kuro--alt-modified calls kuro--schedule-immediate-render."
  (let ((rendered nil))
    (cl-letf (((symbol-function 'kuro--send-key)
               (lambda (_data) nil))
              ((symbol-function 'kuro--schedule-immediate-render)
               (lambda () (setq rendered t))))
      (kuro--alt-modified ?a)
      (should rendered))))

;;; Group 9: All arrows send one string per call (no extra output)

(ert-deftest kuro-input-keys--arrows-send-exactly-one-string ()
  "Each arrow key handler sends exactly one string per invocation."
  (dolist (entry kuro-input-keys-test--arrow-sequences)
    (kuro-input-keys-test--with-cursor-mode nil
      (kuro-input-keys-test--with-capture
        (funcall (car entry))
        (should (= (length kuro-input-keys-test--sent) 1))))))

;;; Group 10: Navigation keys same-sequence in both modes

(kuro-input-keys-test--deftest-same-sequence-navigation-cases)

(provide 'kuro-input-keys-test)
;;; kuro-input-keys-test.el ends here
