;;; kuro-mux-ext2.el --- kuro-mux: layout persistence, prefix keymap, broadcast, setup  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 takeokunn

;;; Commentary:

;; Continuation of kuro-mux-ext.el (split to keep files under 600 lines).
;; Provides: layout save/restore, prefix keymap, help, clock, broadcast, setup.
;; Loaded by kuro-mux.el after kuro-mux-ext.el; relies on load order for
;; kuro-mux--install-hooks, kuro-mux--live-sessions, and kuro-mux-ext vars.

;;; Code:

(require 'kuro-keymap)
(require 'kuro-mux-monitor)

(declare-function kuro-mux--live-sessions      "kuro-mux" ())
(declare-function kuro-mux--for-each-live-session "kuro-mux" (fn &optional exclude))
(declare-function kuro-mux--install-hooks      "kuro-mux-ext" ())
(declare-function kuro-mux--register           "kuro-mux" ())
(declare-function kuro-mux-install-mode-line   "kuro-mux" ())
(declare-function kuro-mux-next                "kuro-mux" ())
(declare-function kuro-mux-prev                "kuro-mux" ())
(declare-function kuro-mux-switch-by-name      "kuro-mux" (name))
(declare-function kuro-mux-other-window        "kuro-mux" ())
(declare-function kuro-mux-rotate-panes        "kuro-mux" (&optional backward))
(declare-function kuro-mux-rotate-panes-backward "kuro-mux" ())
(declare-function kuro-mux-last                "kuro-mux-windows" ())
(declare-function kuro-mux-find-window         "kuro-mux-windows" (name))
(declare-function kuro-mux-select-by-index     "kuro-mux" (n))
(declare-function kuro-mux-split-right         "kuro-mux-windows" (&optional command))
(declare-function kuro-mux-split-below         "kuro-mux-windows" (&optional command))
(declare-function kuro-mux-detach              "kuro-mux-windows" ())
(declare-function kuro-mux-zoom                "kuro-mux-windows" ())
(declare-function kuro-mux-kill                "kuro-mux-windows" ())
(declare-function kuro-mux-swap-pane-forward   "kuro-mux-windows" ())
(declare-function kuro-mux-swap-pane-backward  "kuro-mux-windows" ())
(declare-function kuro-mux-resize-pane         "kuro-mux-windows" (direction &optional delta))
(declare-function kuro-mux-break-pane          "kuro-mux-windows" ())
(declare-function kuro-mux-join-pane           "kuro-mux-windows" ())
(declare-function kuro-mux-rename              "kuro-mux-windows" ())
(declare-function kuro-mux-send-to-session     "kuro-mux-windows" ())
(declare-function kuro-mux-next-layout         "kuro-mux-layout" ())
(declare-function kuro-mux-previous-layout     "kuro-mux-layout" ())
(declare-function kuro-mux-select-layout       "kuro-mux-layout" (layout))
(declare-function kuro-create                  "kuro" (&optional command))
(declare-function kuro--send-paste-or-raw      "kuro" (text))
(declare-function kuro-copy-mode               "kuro" ())
(declare-function kuro-search-forward          "kuro" ())
(declare-function kuro-list-sessions           "kuro" ())

;; Buffer-local variables from kuro-mux.el and kuro-mux-ext.el.
(defvar kuro-mux--name)
(defvar kuro-mux--command)
(defvar kuro-mux--directory)
(defvar kuro-mux-mode-line-segment)


;;;; Layout persistence
;; `kuro-mux-layout-file' and `kuro-mux-auto-save-layout' defcustoms are
;; defined in kuro-mux-ext.el (loaded first), so only forward-declare here.
(defvar kuro-mux-layout-file)
(defvar kuro-mux-auto-save-layout)

(defun kuro-mux--session-spec (buf)
  "Return a layout spec plist for kuro buffer BUF.
Returns nil if BUF is not a live kuro buffer."
  (when (buffer-live-p buf)
    (with-current-buffer buf
      (list :name      (or kuro-mux--name (buffer-name))
            :command   (or kuro-mux--command kuro-shell)
            :directory (or kuro-mux--directory default-directory)))))

;;;###autoload
(defun kuro-mux-save-layout ()
  "Save the current kuro session layout to `kuro-mux-layout-file'.
The layout records the name, command, and working directory of each
live session.  The PTY state (scrollback, terminal modes) is NOT saved.
Use `kuro-mux-restore-layout' to recreate the sessions after an Emacs
restart."
  (interactive)
  (let* ((sessions (kuro-mux--live-sessions))
         (specs    (delq nil (mapcar #'kuro-mux--session-spec sessions))))
    (with-temp-file kuro-mux-layout-file
      (insert ";; kuro-mux layout — auto-generated by kuro-mux-save-layout\n")
      (insert ";; Restore with M-x kuro-mux-restore-layout\n")
      (pp `(kuro-mux-layout ,@specs) (current-buffer)))
    (message "kuro-mux: layout saved (%d session%s) → %s"
             (length specs)
             (if (= (length specs) 1) "" "s")
             kuro-mux-layout-file)))

(defun kuro-mux--read-layout-file ()
  "Read and return the layout sexp from `kuro-mux-layout-file'.
Returns nil if the file does not exist or cannot be parsed."
  (when (file-readable-p kuro-mux-layout-file)
    (condition-case nil
        (with-temp-buffer
          (insert-file-contents kuro-mux-layout-file)
          (goto-char (point-min))
          (read (current-buffer)))
      (error nil))))

(defun kuro-mux--restore-session (spec)
  "Recreate a single kuro session from layout SPEC plist.
SPEC must have :command and optionally :name and :directory.
Calls `kuro-mux--register' explicitly after creation so the session
appears in the registry even when lifecycle hooks are not installed."
  (let* ((cmd  (plist-get spec :command))
         (name (plist-get spec :name))
         (dir  (plist-get spec :directory))
         (default-directory (or (and dir (file-directory-p dir) dir)
                                default-directory)))
    (kuro-create cmd)
    ;; kuro-create switches to the new buffer; annotate and register now
    (when (derived-mode-p 'kuro-mode)
      (setq kuro-mux--command cmd)
      (setq kuro-mux--directory (or dir default-directory))
      (when name
        (setq kuro-mux--name name))
      ;; Ensure registration regardless of whether kuro-mode-hook fired
      (kuro-mux--register))))

;;;###autoload
(defun kuro-mux-restore-layout ()
  "Recreate kuro sessions from the saved layout in `kuro-mux-layout-file'.
Each session is restarted with its saved command and working directory.
Terminal content (scrollback, history) is not restored — only the
session structure is recreated.
Signals `user-error' if the layout file does not exist."
  (interactive)
  (let ((layout (kuro-mux--read-layout-file)))
    (unless layout
      (user-error "Kuro-mux: no layout file found at %s"
                  kuro-mux-layout-file))
    ;; layout = (kuro-mux-layout :name N :command C :directory D ...)
    (unless (eq (car layout) 'kuro-mux-layout)
      (user-error "Kuro-mux: invalid layout file format"))
    (let* ((raw   (cdr layout))
           (specs (kuro-mux--parse-layout-plists raw)))
      (dolist (spec specs)
        (kuro-mux--restore-session spec))
      (message "kuro-mux: restored %d session%s from %s"
               (length specs)
               (if (= (length specs) 1) "" "s")
               kuro-mux-layout-file))))

(defun kuro-mux--parse-layout-plists (raw)
  "Parse RAW (the cdr of a kuro-mux-layout sexp) into a list of session plists.
RAW is a list of plists, each with :name, :command, and :directory keys,
as written by `kuro-mux-save-layout' via `pp'.  Invalid entries (non-list
or missing :command) are silently dropped."
  (seq-filter (lambda (spec)
                (and (listp spec) (plist-member spec :command)))
              raw))


 (eval-and-compile
  (defconst kuro-mux--prefix-bindings
    '(("n" . kuro-mux-next)
      ("p" . kuro-mux-prev)
      ("s" . kuro-mux-switch-by-name)
      ("L" . kuro-mux-last)
      ("o" . kuro-mux-other-window)
      ("C-o" . kuro-mux-rotate-panes)
      ("M-o" . kuro-mux-rotate-panes-backward)
      ("f" . kuro-mux-find-window)
      ("%" . kuro-mux-split-right)
      ("\"" . kuro-mux-split-below)
      ("c" . kuro-mux-create)
      ("," . kuro-mux-rename)
      ("$" . kuro-mux-rename)
      ("d" . kuro-mux-detach)
      ("z" . kuro-mux-zoom)
      ("&" . kuro-mux-kill)
      ("S" . kuro-mux-save-layout)
      ("R" . kuro-mux-restore-layout)
      ("SPC" . kuro-mux-next-layout)
      ("M-SPC" . kuro-mux-select-layout)
      ("M-{" . kuro-mux-previous-layout)
      ("M-}" . kuro-mux-next-layout)
      ("{" . kuro-mux-swap-pane-backward)
      ("}" . kuro-mux-swap-pane-forward)
      ("!" . kuro-mux-break-pane)
      ("@" . kuro-mux-join-pane)
      ("[" . kuro-copy-mode)
      ("/" . kuro-search-forward)
      ("t" . kuro-mux-clock)
      ("x" . kuro-mux-send-to-session)
      ("B" . kuro-mux-broadcast-toggle)
      ("P" . kuro-mux-pipe-pane)
      ("m" . kuro-mux-monitor-activity-toggle)
      ("M" . kuro-mux-monitor-silence)
      ("w" . kuro-list-sessions)
      ("?" . kuro-mux-help))
    "Static prefix bindings for `kuro-mux-prefix-map'.
Each entry is (KEY . COMMAND), where KEY is a `kbd' string.")

  (defconst kuro-mux--prefix-resize-bindings
    '(("<up>" up 2)
      ("<down>" down 2)
      ("<left>" left 5)
      ("<right>" right 5))
    "Resize bindings for `kuro-mux-prefix-map'.
Each entry is (KEY DIRECTION DELTA).")
  )

(eval-and-compile
  (defun kuro-mux--prefix-resize-command (binding)
    "Return a resize command closure for BINDING.
BINDING is one entry from `kuro-mux--prefix-resize-bindings'."
    (pcase-let ((`(,_key ,direction ,delta) binding))
      (lambda () (interactive) (kuro-mux-resize-pane direction delta)))))

(defvar kuro-mux-prefix-map
  (let ((map (make-sparse-keymap)))
    (kuro--define-key-bindings map kuro-mux--prefix-bindings
                               (lambda (binding) (kbd (car binding)))
                               #'cdr)
    (dotimes (i 9)
      (let ((n (1+ i)))
        (define-key map (kbd (number-to-string n))
          (lambda () (interactive) (kuro-mux-select-by-index n)))))
    (kuro--define-key-bindings map kuro-mux--prefix-resize-bindings
                               (lambda (binding) (kbd (car binding)))
                               #'kuro-mux--prefix-resize-command)
    map)
  "Prefix keymap for kuro-mux multiplexer commands.
Bound under `kuro-mux-prefix-key' by `kuro-mux-install-keys'.
Static bindings are driven by `kuro-mux--prefix-bindings'; numeric and
resize bindings are installed procedurally because they close over
runtime values.")

(defcustom kuro-mux-prefix-key "C-c m"
  "Key sequence under which `kuro-mux-prefix-map' is bound.
The value is a `kbd' string used by `kuro-mux-install-keys'.  The default
coexists with the existing terminal-control bindings because the prefix ends
with a plain letter rather than another control character.  Changing this
after `kuro-mux-install-keys' has run requires re-running it."
  :type 'string
  :group 'kuro)

;;;###autoload
(defun kuro-mux-create (&optional command)
  "Create a new kuro session in the current window.
COMMAND defaults to `kuro-shell'.  Provided as a mux-prefix-friendly
wrapper around `kuro-create' so the prefix map has a `c' (create)
binding analogous to tmux."
  (interactive)
  (kuro-create (or command kuro-shell)))

;;;###autoload
(defun kuro-mux-install-keys (&optional keymap)
  "Bind `kuro-mux-prefix-map' under `kuro-mux-prefix-key' in KEYMAP.
KEYMAP defaults to `kuro-mode-map' so the multiplexer prefix is available
in every kuro terminal buffer.  Call this once after loading kuro, e.g.
from `kuro-mux-setup' or your init file.  Returns the keymap modified."
  (let ((map (or keymap (and (boundp 'kuro-mode-map) kuro-mode-map))))
    (unless (keymapp map)
      (user-error "Kuro-mux-install-keys: no valid keymap to bind into"))
    (define-key map (kbd kuro-mux-prefix-key) kuro-mux-prefix-map)
    map))


;;;; Help

(defun kuro-mux--help-insert ()
  "Insert the standard `kuro-mux-help' content into the current buffer."
  (insert (format "kuro-mux prefix key: %s\n\n" kuro-mux-prefix-key))
  (insert "Available commands:\n\n")
  (insert (substitute-command-keys "\\{kuro-mux-prefix-map}")))

;;;###autoload
(defun kuro-mux-help ()
  "Show a help buffer listing all kuro-mux prefix keymap bindings.
Displays the formatted contents of `kuro-mux-prefix-map' and the
configured `kuro-mux-prefix-key' via `with-help-window'."
  (interactive)
  (with-help-window "*kuro-mux help*"
    (kuro-mux--help-insert)))

;;;###autoload
(defun kuro-mux-clock ()
  "Display the current time in the echo area.
Analogous to tmux's clock mode (prefix + t)."
  (interactive)
  (message "kuro-mux: %s" (format-time-string "%H:%M:%S")))


;;;; Broadcast (synchronized panes)

(defvar kuro-mux--broadcast-mode nil
  "When non-nil, PTY input is replicated to all live kuro sessions.
Toggle interactively with `kuro-mux-broadcast-toggle' (prefix key + B).
Analogous to tmux's `:setw synchronize-panes on'.")

(defvar kuro-mux--broadcasting nil
  "Non-nil while `kuro-mux--broadcast-send' is iterating sessions.
Prevents re-entrant advice calls from causing infinite recursion when
broadcasting triggers another `kuro--send-paste-or-raw' in a target buffer.")

(defun kuro-mux--broadcast-send (text)
  "Replicate TEXT to all live kuro sessions except the current buffer.
Installed as :after advice on `kuro--send-paste-or-raw'.  Has no effect
when `kuro-mux--broadcast-mode' is nil or a broadcast is already in
progress (`kuro-mux--broadcasting' non-nil)."
  (when (and kuro-mux--broadcast-mode (not kuro-mux--broadcasting))
    (let ((kuro-mux--broadcasting t)
          (origin (current-buffer)))
      (kuro-mux--for-each-live-session
       (lambda (buf)
         (with-current-buffer buf
           (kuro--send-paste-or-raw text)))
       origin))))

;;;###autoload
(defun kuro-mux-broadcast-toggle ()
  "Toggle broadcast mode: replicate PTY input to all live kuro sessions.
When enabled, every keystroke sent to any kuro buffer is mirrored to all
other live kuro sessions — useful for running the same command on multiple
servers simultaneously.  Analogous to tmux `:setw synchronize-panes'."
  (interactive)
  (setq kuro-mux--broadcast-mode (not kuro-mux--broadcast-mode))
  (message "kuro-mux broadcast: %s"
           (if kuro-mux--broadcast-mode "ON — input shared across all sessions"
             "OFF")))

;; Install relay at load time; the guard inside kuro-mux--broadcast-send
;; ensures it is a no-op (two variable reads) unless broadcast mode is on.
(advice-add 'kuro--send-paste-or-raw :after #'kuro-mux--broadcast-send)


;;;; Setup

(defcustom kuro-mux-install-prefix-keys t
  "When non-nil, `kuro-mux-setup' installs the mux prefix keymap.
Binds `kuro-mux-prefix-map' under `kuro-mux-prefix-key' in `kuro-mode-map'.
Set to nil if you prefer to bind multiplexer commands manually."
  :type 'boolean
  :group 'kuro)

(defun kuro-mux-setup ()
  "Activate kuro-mux: install lifecycle hooks and (optionally) prefix keys.
Call this once in your init file after loading kuro.
Installs the tmux-style prefix keymap when `kuro-mux-install-prefix-keys'
is non-nil.  With `kuro-mux-tab-bar-mode' enabled, also syncs sessions to
tab-bar tabs."
  (kuro-mux--install-hooks)
  (when (and kuro-mux-install-prefix-keys
             (boundp 'kuro-mode-map)
             (keymapp kuro-mode-map))
    (kuro-mux-install-keys))
  (when kuro-mux-mode-line-segment
    (kuro-mux-install-mode-line)))


(provide 'kuro-mux-ext2)
;;; kuro-mux-ext2.el ends here
