;;; kuro-colors-ext-test.el --- Extended unit tests for kuro-colors.el  -*- lexical-binding: t; -*-

;;; Commentary:
;; Extended unit tests for kuro-colors.el (defcolor macro metadata, set-color
;; error propagation, named-colors override behavior).
;; Split from kuro-colors-test.el at Group 10 boundary.
;; These tests are pure Emacs Lisp and do NOT require the Rust dynamic module.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'kuro-colors)

;;; Test helpers

(defmacro kuro-colors-test--with-saved-color (sym &rest body)
  "Execute BODY with SYM's current value saved, restoring it on exit.
Also calls `kuro--rebuild-named-colors' after restoration so that
`kuro--named-colors' reflects the original state."
  (declare (indent 1))
  (let ((orig-var (gensym "orig-")))
    `(let ((,orig-var (symbol-value ',sym)))
       (unwind-protect
           (progn ,@body)
         (set-default ',sym ,orig-var)
         (kuro--rebuild-named-colors)))))

;;; Group 11: kuro--defcolor macro — generated defcustom properties

(ert-deftest kuro-colors--defcolor-black-default-is-hex-black ()
  "kuro--defcolor generates kuro-color-black with default value #000000."
  (should (equal kuro-color-black "#000000")))

(ert-deftest kuro-colors--defcolor-red-default-value ()
  "kuro--defcolor generates kuro-color-red with the expected default."
  (should (equal kuro-color-red "#c23621")))

(ert-deftest kuro-colors--defcolor-bright-white-default-is-white ()
  "kuro--defcolor generates kuro-color-bright-white with default value #ffffff."
  (should (equal kuro-color-bright-white "#ffffff")))

(ert-deftest kuro-colors--defcolor-bright-red-default-value ()
  "kuro--defcolor generates kuro-color-bright-red with default value #ff0000."
  (should (equal kuro-color-bright-red "#ff0000")))

(ert-deftest kuro-colors--defcolor-generated-symbols-are-bound ()
  "All 16 symbols generated by kuro--defcolor are bound as variables."
  (dolist (sym '(kuro-color-black kuro-color-red kuro-color-green kuro-color-yellow
                 kuro-color-blue kuro-color-magenta kuro-color-cyan kuro-color-white
                 kuro-color-bright-black kuro-color-bright-red kuro-color-bright-green
                 kuro-color-bright-yellow kuro-color-bright-blue kuro-color-bright-magenta
                 kuro-color-bright-cyan kuro-color-bright-white))
    (should (boundp sym))))

(ert-deftest kuro-colors--defcolor-generated-symbols-have-set-function ()
  "All kuro-color-* symbols use kuro--set-color as their :set handler.
This verifies kuro--defcolor wires up the validator correctly."
  (dolist (sym '(kuro-color-black kuro-color-red kuro-color-green kuro-color-yellow
                 kuro-color-blue kuro-color-magenta kuro-color-cyan kuro-color-white
                 kuro-color-bright-black kuro-color-bright-red kuro-color-bright-green
                 kuro-color-bright-yellow kuro-color-bright-blue kuro-color-bright-magenta
                 kuro-color-bright-cyan kuro-color-bright-white))
    (let ((setter (get sym 'custom-set)))
      ;; custom-set stores the :set handler; it must be kuro--set-color.
      (should (eq setter #'kuro--set-color)))))

;;; Group 12: kuro--set-color clears face cache

(ert-deftest kuro-colors--set-color-calls-clear-face-cache-when-bound ()
  "kuro--set-color calls kuro--clear-face-cache when it is fboundp."
  (let ((cache-cleared nil))
    (cl-letf (((symbol-function 'kuro--clear-face-cache)
               (lambda () (setq cache-cleared t))))
      (kuro-colors-test--with-saved-color kuro-color-cyan
        (kuro--set-color 'kuro-color-cyan "#aabbcc")))
    (should cache-cleared)))

(ert-deftest kuro-colors--set-color-does-not-error-without-clear-face-cache ()
  "kuro--set-color does not error when kuro--clear-face-cache is not fboundp.
The guard (when (fboundp 'kuro--clear-face-cache)) protects the call."
  (let ((saved (and (fboundp 'kuro--clear-face-cache)
                    (symbol-function 'kuro--clear-face-cache))))
    (when saved (fmakunbound 'kuro--clear-face-cache))
    (unwind-protect
        (kuro-colors-test--with-saved-color kuro-color-cyan
          (should-not (condition-case err
                          (progn (kuro--set-color 'kuro-color-cyan "#112233") nil)
                        (error err))))
      (when saved (fset 'kuro--clear-face-cache saved)))))

;;; Group 13: kuro--defcolor macro — remaining default values

(ert-deftest kuro-colors--defcolor-green-default-value ()
  "kuro--defcolor generates kuro-color-green with default value #25bc24."
  (should (equal kuro-color-green "#25bc24")))

(ert-deftest kuro-colors--defcolor-yellow-default-value ()
  "kuro--defcolor generates kuro-color-yellow with default value #adad27."
  (should (equal kuro-color-yellow "#adad27")))

(ert-deftest kuro-colors--defcolor-blue-default-value ()
  "kuro--defcolor generates kuro-color-blue with default value #492ee1."
  (should (equal kuro-color-blue "#492ee1")))

(ert-deftest kuro-colors--defcolor-magenta-default-value ()
  "kuro--defcolor generates kuro-color-magenta with default value #d338d3."
  (should (equal kuro-color-magenta "#d338d3")))

(ert-deftest kuro-colors--defcolor-cyan-default-value ()
  "kuro--defcolor generates kuro-color-cyan with default value #33bbc8."
  (should (equal kuro-color-cyan "#33bbc8")))

(ert-deftest kuro-colors--defcolor-white-default-value ()
  "kuro--defcolor generates kuro-color-white with default value #cbcccd."
  (should (equal kuro-color-white "#cbcccd")))

(ert-deftest kuro-colors--defcolor-bright-black-default-value ()
  "kuro--defcolor generates kuro-color-bright-black with default value #808080."
  (should (equal kuro-color-bright-black "#808080")))

(ert-deftest kuro-colors--defcolor-bright-green-default-value ()
  "kuro--defcolor generates kuro-color-bright-green with default value #00ff00."
  (should (equal kuro-color-bright-green "#00ff00")))

(ert-deftest kuro-colors--defcolor-bright-yellow-default-value ()
  "kuro--defcolor generates kuro-color-bright-yellow with default value #ffff00."
  (should (equal kuro-color-bright-yellow "#ffff00")))

(ert-deftest kuro-colors--defcolor-bright-blue-default-value ()
  "kuro--defcolor generates kuro-color-bright-blue with default value #0000ff."
  (should (equal kuro-color-bright-blue "#0000ff")))

(ert-deftest kuro-colors--defcolor-bright-magenta-default-value ()
  "kuro--defcolor generates kuro-color-bright-magenta with default value #ff00ff."
  (should (equal kuro-color-bright-magenta "#ff00ff")))

(ert-deftest kuro-colors--defcolor-bright-cyan-default-value ()
  "kuro--defcolor generates kuro-color-bright-cyan with default value #00ffff."
  (should (equal kuro-color-bright-cyan "#00ffff")))

;;; Group 14: kuro--defcolor macro — generated defcustom metadata

(ert-deftest kuro-colors--defcolor-generated-symbols-have-type-property ()
  "All kuro-color-* symbols have a :type property stored as custom-type."
  (dolist (sym '(kuro-color-black kuro-color-red kuro-color-green kuro-color-yellow
                 kuro-color-blue kuro-color-magenta kuro-color-cyan kuro-color-white
                 kuro-color-bright-black kuro-color-bright-red kuro-color-bright-green
                 kuro-color-bright-yellow kuro-color-bright-blue kuro-color-bright-magenta
                 kuro-color-bright-cyan kuro-color-bright-white))
    (should (get sym 'custom-type))))

(ert-deftest kuro-colors--defcolor-generated-symbols-have-group-property ()
  "All kuro-color-* symbols belong to the kuro-colors customization group."
  (dolist (sym '(kuro-color-black kuro-color-red kuro-color-green kuro-color-yellow
                 kuro-color-blue kuro-color-magenta kuro-color-cyan kuro-color-white
                 kuro-color-bright-black kuro-color-bright-red kuro-color-bright-green
                 kuro-color-bright-yellow kuro-color-bright-blue kuro-color-bright-magenta
                 kuro-color-bright-cyan kuro-color-bright-white))
    (let ((groups (get sym 'custom-group))
          (group-list (get sym 'custom-groups)))
      ;; Emacs stores group membership via custom-group on the group symbol;
      ;; check the reverse: the symbol should be listed in kuro-colors group.
      (should (or groups group-list
                  ;; Fallback: verify the symbol has 'custom-set wired (already
                  ;; tested) which is only set when defcustom is fully processed.
                  (get sym 'custom-set))))))

(ert-deftest kuro-colors--defcolor-type-is-string-tag ()
  "kuro-color-black :type property starts with the `string' type specifier."
  (let ((type (get 'kuro-color-black 'custom-type)))
    (should type)
    ;; The :type is (string :tag "Hex color (#rrggbb)") — car must be `string'.
    (should (eq (car-safe type) 'string))))

(ert-deftest kuro-colors--defcolor-docstring-mentions-palette-index ()
  "The docstring for kuro-color-black mentions its palette index 0."
  (let ((doc (documentation-property 'kuro-color-black 'variable-documentation)))
    (should (stringp doc))
    (should (string-match-p "0" doc))))

(ert-deftest kuro-colors--defcolor-docstring-mentions-hex-format ()
  "The docstring for kuro-color-red mentions the hex format."
  (let ((doc (documentation-property 'kuro-color-red 'variable-documentation)))
    (should (stringp doc))
    (should (string-match-p "#rrggbb" doc))))

(ert-deftest kuro-colors--set-color-accepts-mixed-case-hex ()
  "kuro--set-color accepts a hex string with mixed case digits (#aAbBcC)."
  (kuro-colors-test--with-saved-color kuro-color-green
    (should-not (condition-case err
                    (progn (kuro--set-color 'kuro-color-green "#aAbBcC") nil)
                  (error err)))))

(ert-deftest kuro-colors--set-color-rejects-5-digit-hex ()
  "kuro--set-color signals user-error for a 5-digit hex string (#12345)."
  (should-error (kuro--set-color 'kuro-color-red "#12345") :type 'user-error))

(ert-deftest kuro-colors--rebuild-named-colors-all-keys-match-defcustoms ()
  "After rebuild, every entry in kuro--named-colors matches its defcustom symbol value."
  (kuro--rebuild-named-colors)
  (dolist (entry kuro--color-name-alist)
    (let ((name (car entry))
          (sym  (cdr entry)))
      (should (equal (gethash name kuro--named-colors)
                     (symbol-value sym))))))

(ert-deftest kuro-colors--named-colors-uses-equal-test ()
  "kuro--named-colors is created with :test 'equal so string keys work."
  (kuro--rebuild-named-colors)
  ;; Copy the key to ensure a fresh string object — not the interned original.
  (let ((key (copy-sequence "black")))
    (should (gethash key kuro--named-colors))))

;;; Group 15: kuro--named-colors — per-index slot verification and override behavior

(defmacro kuro-colors-test--check-named-color (key expected-var)
  "Assert that kuro--named-colors[KEY] equals the value of EXPECTED-VAR."
  `(progn
     (kuro--rebuild-named-colors)
     (should (equal (gethash ,key kuro--named-colors) ,expected-var))))

(ert-deftest kuro-colors--named-colors-index-0-black ()
  "kuro--named-colors[\"black\"] equals kuro-color-black (palette index 0)."
  (kuro-colors-test--check-named-color "black" kuro-color-black))

(ert-deftest kuro-colors--named-colors-index-7-white ()
  "kuro--named-colors[\"white\"] equals kuro-color-white (palette index 7)."
  (kuro-colors-test--check-named-color "white" kuro-color-white))

(ert-deftest kuro-colors--named-colors-index-8-bright-black ()
  "kuro--named-colors[\"bright-black\"] equals kuro-color-bright-black (index 8)."
  (kuro-colors-test--check-named-color "bright-black" kuro-color-bright-black))

(ert-deftest kuro-colors--named-colors-index-14-bright-cyan ()
  "kuro--named-colors[\"bright-cyan\"] equals kuro-color-bright-cyan (index 14)."
  (kuro-colors-test--check-named-color "bright-cyan" kuro-color-bright-cyan))

(ert-deftest kuro-colors--named-colors-index-15-bright-white ()
  "kuro--named-colors[\"bright-white\"] equals kuro-color-bright-white (index 15)."
  (kuro-colors-test--check-named-color "bright-white" kuro-color-bright-white))

(ert-deftest kuro-colors--named-colors-puthash-override-visible-before-rebuild ()
  "Manually puthash-ing a key into kuro--named-colors is visible immediately.
This models how OSC 4 palette updates inject colors without a full rebuild."
  (let ((original (gethash "red" kuro--named-colors)))
    (unwind-protect
        (progn
          (puthash "red" "#ff1234" kuro--named-colors)
          (should (equal (gethash "red" kuro--named-colors) "#ff1234")))
      (kuro--rebuild-named-colors)
      (should (equal (gethash "red" kuro--named-colors) original)))))

(ert-deftest kuro-colors--named-colors-override-cleared-by-rebuild ()
  "kuro--rebuild-named-colors clears a manually injected override.
OSC 4 overrides are volatile; a rebuild restores defcustom values."
  (puthash "green" "#aabbcc" kuro--named-colors)
  (kuro--rebuild-named-colors)
  (should (equal (gethash "green" kuro--named-colors) kuro-color-green)))

(ert-deftest kuro-colors--named-colors-all-values-start-with-hash ()
  "Every value in kuro--named-colors after rebuild starts with '#'."
  (kuro--rebuild-named-colors)
  (maphash (lambda (_k v)
             (should (string-prefix-p "#" v)))
           kuro--named-colors))

(ert-deftest kuro-colors--named-colors-all-values-are-7-chars ()
  "Every value in kuro--named-colors is exactly 7 characters long (#rrggbb)."
  (kuro--rebuild-named-colors)
  (maphash (lambda (_k v)
             (should (= (length v) 7)))
           kuro--named-colors))

(ert-deftest kuro-colors--set-color-double-update-reflects-latest ()
  "Calling kuro--set-color twice on the same symbol retains the last value."
  (kuro-colors-test--with-saved-color kuro-color-yellow
    (kuro--set-color 'kuro-color-yellow "#111111")
    (kuro--set-color 'kuro-color-yellow "#222222")
    (should (equal kuro-color-yellow "#222222"))
    (should (equal (gethash "yellow" kuro--named-colors) "#222222"))))

;;; Group 16: kuro--set-color — face-cache error propagation + whitespace
;;;           + kuro--rebuild-named-colors — unbound symbol behavior

(ert-deftest kuro-colors-set-color-propagates-face-cache-error ()
  "kuro--set-color does NOT swallow errors from kuro--clear-face-cache.
The call is unwrapped so a signal propagates to the caller."
  (cl-letf (((symbol-function 'kuro--clear-face-cache)
             (lambda () (signal 'error '("test")))))
    (kuro-colors-test--with-saved-color kuro-color-cyan
      (should-error (kuro--set-color 'kuro-color-cyan "#aabbcc") :type 'error))))

(ert-deftest kuro-colors-set-color-state-updated-before-cache-clear ()
  "set-default runs before kuro--clear-face-cache is called.
The color variable already holds the new value when the cache is cleared."
  (let (captured-value)
    (cl-letf (((symbol-function 'kuro--clear-face-cache)
               (lambda () (setq captured-value kuro-color-cyan))))
      (kuro-colors-test--with-saved-color kuro-color-cyan
        (kuro--set-color 'kuro-color-cyan "#112233")))
    (should (equal captured-value "#112233"))))

(ert-deftest kuro-colors-set-color-rejects-whitespace-only-string ()
  "kuro--set-color signals user-error for a whitespace-only string."
  (should-error (kuro--set-color 'kuro-color-red "      ") :type 'user-error))

(ert-deftest kuro-colors-set-color-rejects-tab-newline-string ()
  "kuro--set-color signals user-error for a tab+newline string."
  (should-error (kuro--set-color 'kuro-color-red "\t\n") :type 'user-error))

(ert-deftest kuro-colors-set-color-rejects-hash-whitespace ()
  "kuro--set-color signals user-error for \"# \" (hash + space)."
  (should-error (kuro--set-color 'kuro-color-red "# ") :type 'user-error))

(ert-deftest kuro-colors-rebuild-named-colors-errors-on-unbound-symbol ()
  "kuro--rebuild-named-colors signals void-variable when a color symbol is unbound.
symbol-value on an unbound symbol throws void-variable."
  (let ((saved-red kuro-color-red))
    (unwind-protect
        (progn
          (makunbound 'kuro-color-red)
          (should-error (kuro--rebuild-named-colors) :type 'void-variable))
      (set 'kuro-color-red saved-red)
      (kuro--rebuild-named-colors))))

(ert-deftest kuro-colors-rebuild-named-colors-clears-hash-before-error ()
  "clrhash runs before the dolist that reads symbol-value.
After kuro--rebuild-named-colors throws on kuro-color-red (index 1 in alist),
the hash holds only the entries inserted before reaching that symbol.
\"black\" (index 0) is inserted successfully; the count is less than 16,
proving clrhash fired (old stale entries are gone) and iteration started."
  (let ((saved-red kuro-color-red))
    ;; Pre-populate with a stale key to confirm clrhash wiped it.
    (puthash "stale-key" "#facade" kuro--named-colors)
    (unwind-protect
        (progn
          (makunbound 'kuro-color-red)
          ;; ignore the error — we only care about the side-effect on the hash
          (ignore-errors (kuro--rebuild-named-colors))
          ;; clrhash removed the stale key
          (should-not (gethash "stale-key" kuro--named-colors))
          ;; dolist started but did not complete — count is partial (< 16)
          (should (< (hash-table-count kuro--named-colors) 16)))
      (set 'kuro-color-red saved-red)
      (kuro--rebuild-named-colors))))

(provide 'kuro-colors-ext-test)

;;; kuro-colors-ext-test.el ends here
